export const PostData = [
  {
    id: 1,
    name: 'Pookie',
    avatar: require('./../assets/avatars/1.jpg'),
    likes: 52,
    comments: 3,
    photo: require('./../assets/images/1.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 2,
    name: 'Chum',
    avatar: require('./../assets/avatars/2.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/2.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 3,
    name: 'Goblin',
    avatar: require('./../assets/avatars/3.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/20.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 4,
    name: 'Drake',
    avatar: require('./../assets/avatars/4.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/22.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 5,
    name: 'Juicy',
    avatar: require('./../assets/avatars/5.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/23.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 6,
    name: 'Dorito',
    avatar: require('./../assets/avatars/6.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/24.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
  {
    id: 7,
    name: 'Dearey',
    avatar: require('./../assets/avatars/7.jpg'),
    likes: 34,
    comments: 5,
    photo: require('./../assets/images/25.jpeg'),
    text: 'lorem ipsum bla bla bla',
  },
];
