export const SearchData = [
  [
    [
      {
        id: 1,
        name: 'Pookie',
        avatar: require('./../assets/avatars/1.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/1.jpeg'),
        keyword: 'sea',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 2,
        name: 'Chum',
        avatar: require('./../assets/avatars/2.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/2.jpeg'),
        keyword: 'sea',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 3,
        name: 'Goblin',
        avatar: require('./../assets/avatars/3.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/3.jpeg'),
        keyword: 'women',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 4,
        name: 'Drake',
        avatar: require('./../assets/avatars/4.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/4.jpeg'),
        keyword: 'city',
        text: 'Illusion is the first of all pleasures',
      },
    ],
    [
      {
        id: 5,
        name: 'Juicy',
        avatar: require('./../assets/avatars/5.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/5.jpeg'),
        keyword: 'city',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 6,
        name: 'Dorito',
        avatar: require('./../assets/avatars/6.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/6.jpeg'),
        keyword: 'nature',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 7,
        name: 'Dearey',
        avatar: require('./../assets/avatars/7.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/7.jpeg'),
        keyword: 'city',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 8,
        name: 'Pookie',
        avatar: require('./../assets/avatars/1.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/8.jpeg'),
        keyword: 'women',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 9,
        name: 'Chum',
        avatar: require('./../assets/avatars/2.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/9.jpeg'),
        keyword: 'city',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 10,
        name: 'Goblin',
        avatar: require('./../assets/avatars/3.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/10.jpeg'),
        keyword: 'city',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 11,
        name: 'Drake',
        avatar: require('./../assets/avatars/4.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/11.jpeg'),
        keyword: 'nature',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 12,
        name: 'Juicy',
        avatar: require('./../assets/avatars/5.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/12.jpeg'),
        keyword: 'nature',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 13,
        name: 'Dorito',
        avatar: require('./../assets/avatars/6.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/13.jpeg'),
        keyword: 'nature',
        text: 'lorem ipsum bla bla bla',
      },
    ],
    [
      {
        id: 14,
        name: 'Dearey',
        avatar: require('./../assets/avatars/7.jpg'),
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/14.jpeg'),
        keyword: 'city',
        text: 'lorem ipsum bla bla bla',
      },
    ],
  ],
  [
    [
      {
        id: 15,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/15.jpeg'),
        keyword: 'nature',
      },
    ],
    [
      {
        id: 16,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/16.jpeg'),
        keyword: 'nature',
      },
    ],
    [
      {
        id: 17,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/17.jpeg'),
        keyword: 'sea',
      },
    ],
    [
      {
        id: 18,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/18.jpeg'),
        keyword: 'sea',
      },
    ],
    [
      {
        id: 19,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/19.jpeg'),
        keyword: 'city',
      },
    ],
    [
      {
        id: 20,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/20.jpeg'),
        keyword: 'sea',
      },
    ],
    [
      {
        id: 21,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/21.jpeg'),
        keyword: 'nature',
      },
    ],
    [
      {
        id: 22,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/22.jpeg'),
        keyword: 'nature',
      },
    ],
    [
      {
        id: 23,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/23.jpeg'),
        keyword: 'women',
      },
    ],
    [
      {
        id: 24,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/24.jpeg'),
        keyword: 'sea',
      },
    ],
    [
      {
        id: 25,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/25.jpeg'),
        keyword: 'city',
      },
    ],
    [
      {
        id: 26,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/26.jpeg'),
        keyword: 'nature',
      },
    ],
    [
      {
        id: 27,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/27.jpeg'),
        keyword: 'city',
      },
    ],
    [
      {
        id: 28,
        name: 'P.Kotov',
        likes: 52,
        comments: 3,
        photo: require('./../assets/images/28.jpeg'),
        keyword: 'city',
      },
    ],
  ],
];
